---
- name: copy {{ cashbook.host }}.conf
  template:
    src=cashbook.conf.j2
    dest=/etc/nginx/conf.d/{{ cashbook.host }}.conf
  notify: restart nginx
  tags: nginx

- name: create document root directory
  file:
    path={{ item }}
    state=directory
    mode=0775
    owner=nginx
    group={{ user.name }}
  with_items:
    - /var/www/{{ cashbook.host }}
  tags: nginx