---
- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags: nginx

- name: copy {{ wordpress.host }}.conf
  template:
    src: wordpress.conf.j2
    dest: "/etc/nginx/conf.d/{{ wordpress.host }}.conf"
  notify: restart nginx
  tags: nginx

- name: change firewall rules
  firewalld:
    service: https
    permanent: true
    state: enabled
  notify: restart firewalld
  tags: nginx

- name: copy ssl_certificate
  copy:
    src: server.pem
    dest: /etc/nginx/server.pem
  notify: restart nginx
  tags: nginx

- name: copy ssl_certificate_key
  copy:
    src: server.key
    dest: /etc/nginx/server.key
  notify: restart nginx
  tags: nginx

- name: copy dhparam.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam.pem
  notify: restart nginx
  tags: nginx

- name: create tmp directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: nginx
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /var/tmp/nginx
    - /var/cache/nginx
  tags: nginx

- name: create document root directory
  file:
    path: "/var/www/{{ wordpress.host }}"
    state: directory
    mode: 0775
    owner: nginx
    group: "{{ user.name }}"
  tags: nginx
