---
- name: set timezone
  timezone: name={{ os.timezone }}
  tags:
     - os
     - timezone
  when: os.version == "7"

- name: configure localetime
  file:
    src=/usr/share/zoneinfo/Japan
    dest=/etc/localtime
    state=link
    force=yes
  tags:
    - os
    - timezone
  when: os.version == "6"
