env: "vagrant"

user:
  name: "vagrant"
  password: "{{ 'vagrant'|password_hash('sha512') }}"
  group: "vagrant,wheel"

ssh:
  port: "22"
  hosts_allow: "all"

mysql:
  root_password: "vagrant"
  user: "vagrant"
  password: "vagrant"

mysql_databases:
  - { name: "wordpress", priv: "wordpress.*:ALL" }
  - { name: "cashbook", priv: "cashbook.*:ALL" }

wordpress:
  host: localhost
  host_without_www: host

cashbook:
  host: cashbook.localhost
  ssl_cert: /etc/pki/tls/certs/server.crt;
  ssl_key: /etc/pki/tls/private/server.key;

postfix:
  myhostname: "wordpress"
  mydomain: "wordpress"
