---
- name: copy hosts.allow
  template:
    src=hosts.allow.j2
    dest=/etc/hosts.allow
  tags:
    - tcp_wrapper

- name: copy hosts.deny
  template:
    src=hosts.deny.j2
    dest=/etc/hosts.deny
  tags:
    - tcp_wrapper

