---
- name: install chrony
  yum:
    name=chrony
    state=present
  tags:
    - os
    - chrony

- name: remove default ntp server
  lineinfile:
    dest=/etc/chrony.conf
    state=absent
    regexp={{ item }}
  with_items:
    - '^server 0\.centos\.pool\.ntp\.org iburst'
    - '^server 1\.centos\.pool\.ntp\.org iburst'
    - '^server 2\.centos\.pool\.ntp\.org iburst'
    - '^server 3\.centos\.pool\.ntp\.org iburst'
  notify: restart chronyd
  tags:
    - os
    - chrony

- name: add ntp server
  blockinfile:
    dest: /etc/chrony.conf
    insertafter: '^# Please consider joining the pool'
    block: |
      server ntp1.jst.mfeed.ad.jp iburst
      server ntp2.jst.mfeed.ad.jp iburst
      server ntp3.jst.mfeed.ad.jp iburst
  notify: restart chronyd
  tags:
    - os
    - chrony

- name: start chronyd and enabled at boot
  service:
    name=chronyd
    state=started
    enabled=yes
  tags:
    - os
    - chrony
