---
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  tags:
    - os
    - os-reboot

#- name: wait for starting
#  local_action: wait_for host={{ inventory_hostname }} port={{ ssh.port }} state=started delay=5
#  delegate_to: 127.0.0.1
#  become: false
#  tags:
#    - os
#    - os-reboot

- name: Wait for bootup
  delegate_to: 127.0.0.1
  become: false
  shell: sleep 2 && ssh -p {{ ssh.port }} {{ inventory_hostname }} "echo OK"
  register: result
  until: result.stdout == "OK"
  retries: 300
  delay: 5
  tags:
    - os
    - os-reboot