---
- name: register status of lastlog
  stat: path=/var/log/lastlog
  register: f
  tags:
    - os
    - lastlog

- name: create lastlog
  file:
    path=/var/log/lastlog
    state=touch
    owner=root
    group=root
    mode=0644
  when: not f.stat.exists
  tags:
    - os
    - lastlog
