---
- name: install remi repository
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-{{ os.version }}.rpm"
  tags: php

- name: install php7
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi,remi-php72
  with_items:
      - php
      - php-fpm
      - php-intl
      - php-mbstring
      - php-mysqlnd
      - php-opcache
      - php-soap
      - php-xml
      - php-pecl-apcu
  notify: restart php-fpm
  tags: php

# - name: copy logrotate
#   template:
#     src: logrotate-php-fpm.j2
#     dest: /etc/logrotate.d/php-fpm
#   tags: php

- name: create log directory
  file:
    path: /var/log/php
    state: directory
    mode: 0775
    owner: nginx
    group: "{{ user.name }}"
    recurse: yes
  tags: php

- name: change permission for php-fpm log directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: nginx
    group: "{{ user.name }}"
  with_items:
    - /var/log/php-fpm
  tags: php

- name: change permission for www directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: nginx
    group: "{{ user.name }}"
  with_items:
    - /var/www
    - /var/www/html
  tags: php

- name: set timezone in php.ini
  lineinfile:
    dest: /etc/php.ini
    regexp: "^;?date.timezone ="
    line: "date.timezone = {{ os.timezone }}"
  notify: restart php-fpm
  tags: php

- name: set expose in php.ini
  lineinfile:
    dest: /etc/php.ini
    regexp: "^;?expose_php ="
    line: "expose_php = Off"
  notify: restart php-fpm
  tags: php

- name: set max_execution_time in php.ini
  lineinfile:
    dest: /etc/php.ini
    regexp: "^;?max_execution_time ="
    line: "max_execution_time = {{ php.max_execution_time }}"
  notify: restart php-fpm
  tags: php

- name: set emergency_restart_threshold in php-fpm.conf
  lineinfile:
    dest: /etc/php-fpm.conf
    regexp: "^;?emergency_restart_threshold ="
    line: "emergency_restart_threshold = 3"
  notify: restart php-fpm
  tags: php

- name: set emergency_restart_interval in php-fpm.conf
  lineinfile:
    dest: /etc/php-fpm.conf
    regexp: "^;?emergency_restart_interval ="
    line: "emergency_restart_interval = 1m"
  notify: restart php-fpm
  tags: php

- name: set process_control_timeout in php-fpm.conf
  lineinfile:
    dest: /etc/php-fpm.conf
    regexp: "^;?process_control_timeout ="
    line: "process_control_timeout = 10"
  notify: restart php-fpm
  tags: php

- name: set events.mechanism in php-fpm.conf
  lineinfile:
    dest: /etc/php-fpm.conf
    regexp: "^;?events.mechanism ="
    line: "events.mechanism = epoll"
  notify: restart php-fpm
  tags: php

- name: set user in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^user ="
    line: "user = nginx"
  notify: restart php-fpm
  tags: php

- name: set group in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^group ="
    line: "group = nginx"
  notify: restart php-fpm
  tags: php

- name: set listen in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^listen ="
    line: "listen = 127.0.0.1:9000"
  notify: restart php-fpm
  tags: php

- name: set listen owner in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?listen.owner ="
    line: "listen.owner = nginx"
  notify: restart php-fpm
  tags: php

- name: set listen group in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?listen.group ="
    line: "listen.group = nginx"
  notify: restart php-fpm
  tags: php

- name: set listen mode in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?listen.mode ="
    line: "listen.mode = 664"
  notify: restart php-fpm
  tags: php

- name: set pm in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^pm ="
    line: "pm = static"
  notify: restart php-fpm
  tags: php

- name: set pm.max_children in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^pm.max_children ="
    line: "pm.max_children = 2"
  notify: restart php-fpm
  tags: php

- name: set pm.max_requests in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?pm.max_requests ="
    line: "pm.max_requests = 500"
  notify: restart php-fpm
  tags: php

- name: set request_terminate_timeout in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?request_terminate_timeout ="
    line: "request_terminate_timeout = {{ php.request_terminate_timeout }}"
  notify: restart php-fpm
  tags: php

- name: set catch_workers_output in php-fpm.d/www.conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?catch_workers_output ="
    line: "catch_workers_output = yes"
  notify: restart php-fpm
  tags: php

- name: change session.save_path
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^;?php_value\\[session\\.save_path\\]"
    line: "php_value[session.save_path] = /tmp"
  notify: restart php-fpm
  tags: php

- name: start php-fpm and enable it at boot
  service:
    name: php-fpm
    state: started
    enabled: yes
  tags: php
